joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

yaskawa_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1_s
    - joint_2_l
    - joint_3_u
    - joint_4_r
    - joint_5_b
    - joint_6_t
  gains:
    joint_1_s:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_2_l:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_3_u:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_4_r:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_5_b:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_6_t:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_1_top_joint
    - finger_2_top_joint
    - finger_3_top_joint
    - knife_top_joint
  gains:
    finger_1_top_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_2_top_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_3_top_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    knife_top_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
test_stand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot_base_joint
  gains:
    robot_base_joint:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1