joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1_s
    - joint_2_l
    - joint_3_u
    - joint_4_r
    - joint_5_b
    - joint_6_t
  gains:
    joint_1_s:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_2_l:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_3_u:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_4_r:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_5_b:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1
    joint_6_t:
      p: 10000
      d: 1000
      i: 1
      i_clamp: 1