yaskawa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1_s
    pid: {p: 100000.0, i: 1.0, d: 1000.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2_l
    pid: {p: 100000.0, i: 1.0, d: 1000.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3_u
    pid: {p: 100000.0, i: 1.0, d: 1000.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4_r
    pid: {p: 100000.0, i: 1.0, d: 1000.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5_b
    pid: {p: 100000.0, i: 1.0, d: 1000.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6_t
    pid: {p: 100000.0, i: 1.0, d: 1000.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6_t-tool0
    pid: {p: 100000.0, i: 1.0, d: 1000.0}