test_stand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  base_position_controller:
    type: effort_controllers/JointPositionController
    joint: robot_base_joint
    pid: {p: 100000.0, i: 1.0, d: 1000.0}
